# Runtime environment
runtime: nodejs20

# Optional: instance class
instance_class: F2

# Environment variables (demo credentials)
env_variables:
  DEMO_USERNAME: "testuser"
  DEMO_PASSWORD: "Test@123"

# URL handlers
handlers:
  - url: /.*
    script: auto
